spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydatabase}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_updates: true
          order_inserts: true
          generate_statistics: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  metrics:
    tags:
      application: wallet-service
  endpoint:
    health:
      show-details: always

server:
  tomcat:
    threads:
      max: 200
      min-spare: 20
    accept-count: 100
    max-connections: 10000

logging:
  level:
    ru.kunikhin.ItroomTestTask: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

retry:
  max-attempts: 10
  initial-interval-ms: 50
  multiplier: 2.0
  max-interval-ms: 2000

ratelimiter:
  max-requests: 1000
  time-window-ms: 1000